backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/static/images/uploads"

publish_mode: editorial_workflow

collections:
  - name: "pagina_inicial"
    label: "Página Inicial"
    files:
      - file: "data/hero.json"
        label: "Hero (Topo da Página)"
        name: "hero"
        fields:
          - { name: "titulo", label: "Título", widget: "string" }
          - name: "imagem"
            label: "Imagem"
            widget: "image"
            hint: "Tamanho recomendado: 800x1000px (proporção 4:5)"
          - { name: "cta", label: "Texto do botão", widget: "string" }
          - { name: "cta_link", label: "Link do botão", widget: "string" }
      - file: "data/sobre.json"
        label: "Seção Sobre"
        name: "sobre"
        fields:
          - { name: "titulo", label: "Título", widget: "string" }
          - name: "imagem"
            label: "Imagem"
            widget: "image"
            hint: "Tamanho recomendado: 600x800px (proporção 3:4)"
          - { name: "texto", label: "Texto da Seção", widget: "markdown" }

  - name: "loja"
    label: "Loja"
    files:
      - file: "data/banner.json"
        label: "Banner (Página Shop)"
        name: "banner_shop"
        fields:
          - label: "Imagens do Banner"
            name: "banner_images"
            widget: "list"
            summary: "{{fields.alt}}"
            fields:
              - name: "src_desktop"
                label: "Imagem (Desktop)"
                widget: "image"
                hint: "Tamanho ideal: 1920x640px (proporção 3:1)"
              - name: "src_mobile"
                label: "Imagem (Mobile)"
                widget: "image"
                hint: "Tamanho ideal: 800x1000px (proporção 4:5)"
              - { label: "Texto Alternativo (opcional)", name: "alt", widget: "string", required: false }
      - file: "data/produtos.json"
        label: "Produtos"
        name: "produtos"
        format: "json"
        fields:
          - label: "Produtos"
            name: "produtos"
            widget: "list"
            summary: "{{fields.nome}} — R$ {{fields.preco}} ({{fields.categoria}})"
            fields:
              - { label: "ID/Slug", name: "id", widget: "string", pattern: ["^[a-z0-9-]+$", "Use minúsculas e hífens."] }
              - { label: "Nome", name: "nome", widget: "string" }
              - { label: "Descrição", name: "descricao", widget: "text" }
              - { label: "Preço (R$)", name: "preco", widget: "number", value_type: "float", min: 0 }
              - { label: "Categoria", name: "categoria", widget: "string" }
              - label: "Imagens por Cor"
                name: "imagens_por_cor"
                widget: "list"
                summary: "Cor: {{fields.cor}} ({{fields.imagens_cor.length}} imagem(ns))"
                fields:
                  - { label: "Cor", name: "cor", widget: "string" }
                  - name: "imagens_cor"
                    label: "Imagens desta Cor"
                    widget: "list"
                    hint: "Tamanho ideal para todas as imagens: 800x1000px (proporção 4:5)"
                    field: {label: "Imagem", name: "src", widget: "image"}
              - label: "Tamanhos"
                name: "tamanhos"
                widget: "list"
                field: { label: "Tamanho", name: "tam", widget: "string" }
              - { label: "Destaque na página inicial", name: "destaque", widget: "boolean", default: false }
              - { label: "Disponível para venda", name: "ativo", widget: "boolean", default: true }
              - { label: "Criado em", name: "createdAt", widget: "datetime" }