backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/static/images/uploads"

publish_mode: editorial_workflow

collections:
  - name: "paginas"
    label: "Páginas"
    files:
      - file: "data/hero.json"
        label: "Hero (Página Inicial)"
        name: "hero"
        fields:
          - { name: "titulo", label: "Título", widget: "string" }
          - { name: "imagem", label: "Imagem", widget: "image" }
          - { name: "cta", label: "Texto do botão", widget: "string" }
          - { name: "cta_link", label: "Link do botão", widget: "string" }
      - file: "data/sobre.json"
        label: "Seção Sobre"
        name: "sobre"
        fields:
          - { name: "titulo", label: "Título", widget: "string" }
          - { name: "imagem", label: "Imagem", widget: "image" }
          - { name: "texto", label: "Texto da Seção", widget: "markdown" }
      - file: "data/banner.json"
        label: "Banner (Página Shop)"
        name: "banner_shop"
        fields:
          - label: "Imagens do Banner"
            name: "banner_images"
            widget: "list"
            summary: "{{fields.alt}}"
            fields:
              - { label: "Imagem (Desktop)", name: "src_desktop", widget: "image" }
              - { label: "Imagem (Mobile)", name: "src_mobile", widget: "image" }
              - { label: "Texto Alternativo", name: "alt", widget: "string", required: false }

  - name: "categorias"
    label: "Categorias de Produtos"
    folder: "data/categorias"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome da Categoria", name: "nome", widget: "string" }

  - name: "produtos"
    label: "Produtos"
    folder: "data/produtos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome", name: "nome", widget: "string" }
      - { label: "Descrição", name: "descricao", widget: "text" }
      - { label: "Preço (R$)", name: "preco", widget: "number", value_type: "float", min: 0 }
      - label: "Categoria"
        name: "categoria"
        widget: "relation"
        collection: "categorias"
        search_fields: ["nome"]
        value_field: "nome"
        display_fields: ["nome"]
      - label: "Imagens por Cor"
        name: "imagens_por_cor"
        widget: "list"
        summary: "Cor: {{fields.cor}} ({{fields.imagens_cor.length}} imagem(ns))"
        fields:
          - { label: "Cor", name: "cor", widget: "string" }
          - { label: "Imagens desta Cor", name: "imagens_cor", widget: "list", field: {label: "Imagem", name: "src", widget: "image"} }
      - label: "Tamanhos Disponíveis"
        name: "tamanhos"
        widget: "list"
        field: { label: "Tamanho", name: "tam", widget: "string" }
      - { label: "Produto em Destaque (aparece na pág. inicial)", name: "destaque", widget: "boolean", default: false }
      - { label: "Disponível para venda", name: "ativo", widget: "boolean", default: true }
      - { label: "Criado em", name: "createdAt", widget: "datetime", default: "" }