backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/static/images/uploads"

publish_mode: editorial_workflow

collections:
  - name: "pagina_inicial"
    label: "Página Inicial"
    files:
      - file: "data/hero.json"
        label: "Seção Hero (Topo)"
        name: "hero"
        fields:
          - { name: "titulo", label: "Título", widget: "string" }
          - { name: "imagem", label: "Imagem", widget: "image" } 
          - { name: "cta", label: "Texto do botão", widget: "string" }
          - { name: "cta_link", label: "Link do botão", widget: "string" }
      - file: "data/sobre.json"
        label: "Seção Sobre"
        name: "sobre"
        fields:
          - { name: "titulo", label: "Título", widget: "string" }
          - { name: "imagem", label: "Imagem 800x1000", widget: "image" }
          - { name: "texto", label: "Texto da Seção", widget: "markdown" }

  - name: "loja"
    label: "Loja"
    files:
    - file: "data/produtos.json"
      label: "Produtos e Banner do Shop"
      name: "produtos"
      format: "json"
      fields:
        - label: "Banner da Loja (Shop)"
          name: "hero"
          widget: "list"
          summary: "{{fields.alt}}"
          fields:
            - { label: "Imagem (Desktop - 1920x640px)", name: "src_desktop", widget: "image" }
            - { label: "Imagem (Mobile - 800x1000px)", name: "src_mobile", widget: "image" }
            - { label: "Texto Alternativo (opcional)", name: "alt", widget: "string", required: false }
        - label: "Produtos"
          name: "produtos"
          widget: "list"
          summary: "{{fields.nome}} — R$ {{fields.preco}} ({{fields.categoria}})"
          fields:
            - { label: "ID/Slug", name: "id", widget: "string", pattern: ["^[a-z0-9-]+$", "Use minúsculas e hífens."] }
            - { label: "Nome", name: "nome", widget: "string" }
            - { label: "Descrição", name: "descricao", widget: "text" }
            - { label: "Preço (R$)", name: "preco", widget: "number", value_type: "float", min: 0 }
            - { label: "Categoria", name: "categoria", widget: "select", options: ["Camisetas","Sapatos","Bolsas","Acessórios","Outros"] }
            - label: "Imagens (cada imagem com sua cor)"
              name: "imagens"
              widget: "list"
              fields:
                - { label: "Imagem", name: "src", widget: "image" }
                - { label: "Cor", name: "color", widget: "string", hint: "Nome da cor (rosa, branco...)" }
            - label: "Tamanhos"
              name: "tamanhos"
              widget: "list"
              field: { label: "Tamanho", name: "tam", widget: "string" }
            - { label: "Link (opcional)", name: "link", widget: "string", required: false }
            - { label: "Destaque", name: "destaque", widget: "boolean", default: false }
            - { label: "Disponível", name: "ativo", widget: "boolean", default: true }
            - { label: "Criado em", name: "createdAt", widget: "datetime" }