backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow

collections:
  - name: "loja"
    label: "Loja"
    files:
      - file: "data/produtos.json"
        label: "Produtos"
        name: "produtos"
        format: "json"
        fields:
          - label: "Produtos"
            name: "produtos"
            widget: "list"
            summary: "{{fields.nome}} — R$ {{fields.preco}} ({{fields.categoria}})"
            fields:
              - { label: "ID/Slug", name: "id", widget: "string", pattern: ["^[a-z0-9-]+$", "Use minúsculas e hífens."] }
              - { label: "Nome", name: "nome", widget: "string" }
              - { label: "Descrição", name: "descricao", widget: "text" }
              - { label: "Preço (R$)", name: "preco", widget: "number", value_type: "float", min: 0 }
              - { label: "Categoria", name: "categoria", widget: "select", options: ["Camisetas","Sapatos","Bolsas","Acessórios","Outros"] }
              - { label: "Imagem", name: "imagem", widget: "image" }
              - label: "Cores"
                name: "cores"
                widget: "list"
                field: { label: "Cor", name: "cor", widget: "string" }
              - label: "Tamanhos"
                name: "tamanhos"
                widget: "list"
                field: { label: "Tamanho", name: "tam", widget: "string" }
              - { label: "Link (opcional)", name: "link", widget: "string", required: false }
              - { label: "Destaque", name: "destaque", widget: "boolean", default: false }
              - { label: "Disponível", name: "ativo", widget: "boolean", default: true }
              - { label: "Criado em", name: "createdAt", widget: "datetime" }

      - file: "data/releases.json"
        label: "Releases (Resumo de mudanças)"
        name: "releases"
        format: "json"
        fields:
          - label: "Publicações"
            name: "releases"
            widget: "list"
            summary: "{{fields.titulo}} — {{fields.data}}"
            fields:
              - { label: "Título", name: "titulo", widget: "string" }
              - { label: "Resumo", name: "resumo", widget: "text" }
              - { label: "Data", name: "data", widget: "datetime" }
              - label: "Produtos afetados (IDs)"
                name: "produtos"
                widget: "list"
                field: { label: "ID do produto", name: "id", widget: "string" }
